// Root server layout: applies global styles and mounts client-only ErrorReporter.
import type { Metadata } from "next";
import "./globals.css";
import ErrorReporter from "../components/ErrorReporter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <ErrorReporter />
        {children}
      </body>
    </html>
  );
}
